server:
  port: 8082

eureka:
  instance:
   hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator: 
          enable: true
      routes:
        - id: project-app
          uri: lb://project-app
          predicates:
            - Path=/api/project/**
          filters:
            - StripPrefix=2
        - id: user-app
          uri: lb://user-app
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
            - AuthFilter
        - id: task-app
          uri: lb://task-app
          predicates:
            - Path=/api/task/**
          filters:
            - StripPrefix=2
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2